name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Frontend build
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Install frontend dependencies
        run: |
          cd client
          npm install

      - name: Build frontend
        run: |
          cd client
          npm run build

      # Backend deployment
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      - name: Install backend dependencies
        run: |
          pip install -r server/requirements.txt

      - name: Run server
        run: |
          python3 server/main.py
