name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Frontend build
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Install frontend dependencies
        run: |
          cd client
          npm install

      - name: Build frontend
        run: |
          cd client
          npm run build

      # Backend deployment
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      - name: Install backend dependencies
        run: |
          cd server 
          pip install -r req.txt

      - name: Run server
        run: gunicorn -w 4 -b 0.0.0.0:10000 main:app --log-level debug

      - name: Deploy to Azure App Service
        uses: azure/webapps-deploy@v2
        with:
          app-name: openb-server
          slot-name: production
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
